pipeline {
    agent {
        kubernetes {
            label 'kubeagent'
            podTemplate {
                label 'kubeagent'
                containerTemplate {
                    name 'maven'
                    image 'maven:3-alpine'
                }
                containerTemplate {
                    name 'jnlp'
                    image 'jenkins/inbound-agent:latest'
                }
            }
    }
  }
    stages {
        stage('Build') {
            steps {
                container('maven') {
                    sh 'mvn clean install'
                }
            }
        }
    }
}
